AWSTemplateFormatVersion: '2010-09-09'
Description: 'Worthy App - Main Stack'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production
    Description: Environment name
  
  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Database master password (min 8 characters)
  
  DBUsername:
    Type: String
    Default: worthy_admin
    Description: Database master username

Resources:
  # VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${DeploymentBucket}/cloudformation/vpc.yaml'
      Parameters:
        Environment: !Ref Environment

  # RDS Stack
  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${DeploymentBucket}/cloudformation/rds.yaml'
      Parameters:
        Environment: !Ref Environment
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        DBSecurityGroup: !GetAtt VPCStack.Outputs.DBSecurityGroup
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword

  # Lambda Stack
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: RDSStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${DeploymentBucket}/cloudformation/lambda.yaml'
      Parameters:
        Environment: !Ref Environment
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        LambdaSecurityGroup: !GetAtt VPCStack.Outputs.LambdaSecurityGroup
        DatabaseURL: !GetAtt RDSStack.Outputs.DatabaseURL
        DeploymentBucket: !Ref DeploymentBucket

  # API Gateway Stack
  APIStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${DeploymentBucket}/cloudformation/api-gateway.yaml'
      Parameters:
        Environment: !Ref Environment
        LambdaFunctionArn: !GetAtt LambdaStack.Outputs.LambdaFunctionArn

  # S3 and CloudFront Stack
  FrontendStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${DeploymentBucket}/cloudformation/frontend.yaml'
      Parameters:
        Environment: !Ref Environment

  # Deployment bucket for CloudFormation templates and Lambda code
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'worthy-deployment-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  FrontendURL:
    Description: CloudFront URL for frontend
    Value: !GetAtt FrontendStack.Outputs.CloudFrontURL
    Export:
      Name: !Sub '${AWS::StackName}-FrontendURL'
  
  APIURL:
    Description: API Gateway URL
    Value: !GetAtt APIStack.Outputs.APIURL
    Export:
      Name: !Sub '${AWS::StackName}-APIURL'
  
  DatabaseEndpoint:
    Description: RDS Database Endpoint
    Value: !GetAtt RDSStack.Outputs.DatabaseEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseEndpoint'
