AWSTemplateFormatVersion: '2010-09-09'
Description: 'Worthy App - RDS PostgreSQL Database'

Parameters:
  Environment:
    Type: String
  VPCId:
    Type: String
  PrivateSubnet1:
    Type: String
  PrivateSubnet2:
    Type: String
  DBSecurityGroup:
    Type: String
  DBUsername:
    Type: String
    Default: worthy_admin
  DBPassword:
    Type: String
    NoEcho: true

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Worthy RDS
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      Tags:
        - Key: Name
          Value: !Sub 'worthy-db-subnet-group-${Environment}'

  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub 'worthy-db-${Environment}'
      Engine: postgres
      EngineVersion: '15.4'
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      StorageType: gp3
      StorageEncrypted: true
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: worthy
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      BackupRetentionPeriod: 7
      PreferredBackupWindow: '03:00-04:00'
      PreferredMaintenanceWindow: 'sun:04:00-sun:05:00'
      MultiAZ: false
      PubliclyAccessible: false
      EnableCloudwatchLogsExports:
        - postgresql
      Tags:
        - Key: Name
          Value: !Sub 'worthy-db-${Environment}'

  # Secrets Manager for database credentials
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'worthy-db-credentials-${Environment}'
      Description: Database credentials for Worthy app
      SecretString: !Sub |
        {
          "username": "${DBUsername}",
          "password": "${DBPassword}",
          "engine": "postgres",
          "host": "${DBInstance.Endpoint.Address}",
          "port": ${DBInstance.Endpoint.Port},
          "dbname": "worthy"
        }

Outputs:
  DatabaseEndpoint:
    Description: RDS Database Endpoint
    Value: !GetAtt DBInstance.Endpoint.Address
  
  DatabasePort:
    Description: RDS Database Port
    Value: !GetAtt DBInstance.Endpoint.Port
  
  DatabaseURL:
    Description: Full Database Connection URL
    Value: !Sub 'postgresql://${DBUsername}:${DBPassword}@${DBInstance.Endpoint.Address}:${DBInstance.Endpoint.Port}/worthy'
  
  DBSecretArn:
    Description: ARN of the database credentials secret
    Value: !Ref DBSecret
